---
- name: Configure Capsule host repositories using Satellite
  hosts: capsules
  become: true
  gather_facts: true
  tasks:
    - name: Generate registration command
      become: false
      redhat.satellite.registration_command:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        validate_certs: "{{ satellite_validate_certs }}"
        insecure: "{{ not satellite_validate_certs }}"
        jwt_expiration: 1
        #smart_proxy: satellite.example.com
        activation_keys:
          - AK_Test_RHEL_9_Capsule
        #hostgroup: HG_Capsules
        setup_insights: true
        setup_remote_execution: false
        setup_remote_execution_pull: true
        setup_container_registry_certs: true
        #remote_execution_interface: net0
        update_packages: false
        # https://github.com/theforeman/foreman-ansible-modules/issues/1975
        #packages:
        #  - foreman_scap_client_bash
        #  - katello-host-tools-tracer
        packages: >
          foreman_scap_client_bash
          katello-host-tools-tracer
      register: registration_command
      delegate_to: localhost
      run_once: true

    - name: Register Capsule to Satellite
      # noqa: command-instead-of-shell
      ansible.builtin.shell:
        cmd: "{{ registration_command.registration_command }}"
      changed_when: true
