---
- name: Install Red Hat Satellite Capsule
  hosts: capsules
  become: true
  vars_files:
    - vault_satellite.yml
  roles:
    - myllynen.satellite_automation.capsule_generate_certs
    - myllynen.satellite_automation.capsule_install
