---
namespace: myllynen
name: satellite_automation
version: "1.6.0"
readme: README.md
authors:
  - Marko Myllynen <myllynen@redhat.com>
description: >
  Ansible playbooks and roles for Red Hat Satellite automation.
license:
  - GPL-3.0-or-later
tags:
  - rhel
  - linux
  - tools
  - satellite
  - capsule
  - automation
  - configuration
  - infrastructure
dependencies:
  ansible.posix: ">=1.5.4"
  redhat.satellite: ">=4.0.0"
repository: https://www.github.com/myllynen/satellite-automation
issues: https://www.github.com/myllynen/satellite-automation/issues
