namespace: myllynen
name: satellite_automation
version: "0.3.0"
readme: README.md
authors:
  - Marko Myllynen <myllynen@redhat.com>
description: >
  Ansible playbooks and roles for Red Hat Satellite automation.
license:
  - GPL-3.0-or-later
tags:
  - rhel
  - satellite
  - capsule
  - automation
  - configuration
dependencies:
  ansible.posix: ">=1.4.0"
  redhat.satellite: ">=3.6.0"
repository: https://www.github.com/myllynen/satellite-automation
issues: https://www.github.com/myllynen/satellite-automation/issues
