---
- name: Install Red Hat Satellite
  hosts: satellite
  become: true
  gather_facts: true
  tasks:
    - name: Verify correct Satellite URL format
      ansible.builtin.assert:
        that:
          - satellite_server_url is defined
          - satellite_server_url is string
          - satellite_server_url.startswith("http://") or
            satellite_server_url.startswith("https://")
        quiet: true
        fail_msg: "Satellite URL must start with http:// or https://."

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - podman
          - satellite
          - sos
        state: present

    - name: Check Satellite status
      redhat.satellite.status_info:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: false
      register: satellite_info
      failed_when:
        - satellite_info.msg is defined
        - "'Unauthorized' in satellite_info.msg"

    - name: Check Red Hat container registry login status
      ansible.builtin.command: >
        podman login --authfile /etc/foreman/registry-auth.json --get-login registry.redhat.io
      register: podman_check
      failed_when: false
      changed_when: false
      when:
        - inventory_hostname in groups.satellite
        - "'--enable-iop' in satellite_installer_options"
        - (satellite_info.msg is defined and 'Connection refused' in satellite_info.msg) or
          (satellite_info.status.result is defined and satellite_info.status.result != 'ok')

    - name: Login to Red Hat container registry
      no_log: true
      ansible.builtin.shell: >
        set -o pipefail &&
        echo '{{ satellite_rhsm_password }}' |
        podman login --authfile /etc/foreman/registry-auth.json
        --username {{ satellite_rhsm_username }} --password-stdin
        registry.redhat.io
      changed_when: true
      when:
        - podman_check is not skipped
        - "'not logged in' in podman_check.stderr"

    - name: Install Satellite
      ansible.builtin.include_role:
        name: redhat.satellite_operations.installer
      register: satellite_install
      when: >
        (satellite_info.msg is defined and 'Connection refused' in satellite_info.msg) or
        (satellite_info.status.result is defined and satellite_info.status.result != 'ok')

    - name: Run post-install health check
      ansible.builtin.command: satellite-maintain health check --plaintext
      changed_when: false
      when: satellite_install is changed
