---
- name: Sync Satellite enabled repositories
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Get product and repository information
      redhat.satellite.resource_info:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_organization }}"
        resource: products
      register: available_products

    - name: Sync enabled product repositories
      redhat.satellite.repository_sync:
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_organization }}"
        product: "{{ item.name }}"
      loop: "{{ available_products.resources | selectattr('repository_count', 'gt', 0) }}"
      loop_control:
        label: "{{ item.name }}"
