---
- name: Sync Satellite repositories
  hosts: satellite
  become: true
  vars_files:
    - vars_satellite.yml
    - vault_satellite.yml
  roles:
    - myllynen.satellite_automation.satellite_sync_repositories
