---
- name: Configure Red Hat Satellite
  hosts: satellite
  become: true
  vars_files:
    - vars_satellite.yml
    - vault_satellite.yml
  roles:
    - redhat.satellite.repositories
    - redhat.satellite.sync_plans
    - redhat.satellite.lifecycle_environments
