---
- name: Fail if invalid Satellite URL defined
  fail:
    msg: "Satellite URL must start with http:// or https://."
  when:
    - not satellite_server_url | default(true) or
      (not satellite_server_url.startswith("http://") and
       not satellite_server_url.startswith("https://"))

- name: Enable Satellite module stream
  command: >
    dnf -y module enable
    satellite:el{{ ansible_facts.distribution_major_version }}
  register: dnf_command
  changed_when: "'Nothing to do' not in dnf_command.stdout"

- name: Install Satellite packages
  dnf:
    name:
      - firewalld
      - glibc-langpack-en
      - insights-client
      - rhc
      - rhc-worker-playbook
      - satellite
      - sos
    state: present

- name: Enable firewalld service
  service:
    name: firewalld
    enabled: true

- name: Start firewalld service
  service:
    name: firewalld
    state: started

- name: Configure Satellite firewall
  ansible.posix.firewalld:
    service: RH-Satellite-6
    zone: "{{ satellite_firewall_zone }}"
    state: enabled
    immediate: true
    permanent: true

- name: Check Satellite status
  redhat.satellite.status_info:
    server_url: "{{ satellite_server_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    validate_certs: false
  register: satellite_info
  failed_when:
    - "'msg' in satellite_info"
    - "'Unauthorized' in satellite_info.msg"

- name: Install Satellite
  environment:
    LC_ALL: en_US.UTF-8
  command: >
    satellite-installer --scenario satellite
    --foreman-initial-admin-username "{{ satellite_username }}"
    --foreman-initial-admin-password '{{ satellite_password }}'
    --foreman-initial-organization "{{ satellite_organization }}"
    --foreman-initial-location "{{ satellite_location }}"
    {{ satellite_installer_custom_parameters }}
  register: satellite_install
  changed_when: true
  when: >
    ('msg' in satellite_info and "Connection refused" in satellite_info.msg) or
    ('result' in satellite_info.status and satellite_info.status.result != "ok")

- name: Verify Satellite status
  redhat.satellite.status_info:
    server_url: "{{ satellite_server_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    validate_certs: "{{ satellite_validate_certs }}"
  register: satellite_info

- name: Connect Satellite to Red Hat Insights
  command: satellite-installer --register-with-insights
  changed_when: true
  when:
    - satellite_register_insights | bool
    - satellite_install is changed
    - ('result' in satellite_info.status and satellite_info.status.result == 'ok')
