---
- name: Get all products
  redhat.satellite.resource_info:
    server_url: "{{ satellite_server_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    organization: "{{ satellite_organization }}"
    resource: products
    validate_certs: "{{ satellite_validate_certs }}"
  register: enabled_products

- name: Sync enabled repositories
  redhat.satellite.repository_sync:
    server_url: "{{ satellite_server_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    organization: "{{ satellite_organization }}"
    product: "{{ item.name }}"
    validate_certs: "{{ satellite_validate_certs }}"
  loop: "{{ enabled_products.resources }}"
  when: item.repository_count > 0
