---
- name: Generate Satellite Capsule certificates
  throttle: 1
  command:
    cmd: >
      capsule-certs-generate
      --foreman-proxy-fqdn {{ inventory_hostname }}
      --certs-tar /root/{{ inventory_hostname }}-certs.tar
    creates: /root/{{ inventory_hostname }}-certs.tar
  delegate_to: "{{ groups.satellite[0] }}"
