---
- name: Install Red Hat Satellite Capsule
  hosts: "{{ capsules | default('all') }}"
  become: true
  gather_facts: true
  roles:
    - myllynen.satellite_automation.capsule_generate_certs
    - myllynen.satellite_automation.capsule_install
