---
- name: Upload Satellite manifest
  hosts: "{{ satellite | default('satellite') }}"
  become: true
  vars:
    satellite_manifest_download: false
    # Manifest file to copy to target
    satellite_manifest_file: /root/satellite_manifest.zip
    #satellite_manifest_uuid:
    satellite_manifest_refresh: true
  vars_files:
    - "{{ inventory_dir + '/vars_satellite.yml' }}"
    - "{{ inventory_dir + '/vault_satellite.yml' }}"
  roles:
    - myllynen.satellite_automation.satellite_manifest
