---
- name: Configure Red Hat Satellite
  hosts: "{{ satellite | default('satellite') }}"
  become: true
  roles:
    - redhat.satellite.repositories
    - redhat.satellite.sync_plans
    - redhat.satellite.lifecycle_environments
