---
- name: Configure Red Hat Satellite
  hosts: "{{ satellite | default('satellite') }}"
  become: true
  vars_files:
    - "{{ inventory_dir + '/vars_satellite.yml' }}"
    - "{{ inventory_dir + '/vault_satellite.yml' }}"
  roles:
    - redhat.satellite.repositories
    - redhat.satellite.sync_plans
    - redhat.satellite.lifecycle_environments
