---
- name: Install Red Hat Satellite
  hosts: "{{ satellite | default('satellite') }}"
  become: true
  vars_files:
    - "{{ inventory_dir + '/vars_satellite.yml' }}"
    - "{{ inventory_dir + '/vault_satellite.yml' }}"
  roles:
    - myllynen.satellite_automation.satellite_install
